apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-demo
  labels:
    app: replicaset-demo
spec:
  replicas: 1
  template:
    metadata:
      name: replicaset-demo
      labels:
        app: replicaset-demo
    spec:
      containers:
        - name: replicaset-demo
          image: nginx:1.17.10-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 90
              name: http
      restartPolicy: Always
  selector:
    matchLabels:
      app: replicaset-demo
