before_script:
  - go env -w GOPROXY=https://goproxy.cn,direct
  - go env -w GO111MODULE=on
stages:
  - build
  - test
  - docker-deploy
build:
  stage: build
  script:
    - go mod tidy
    - make
  only:
    - tags
test:
  stage: test
  script:
    - echo $CI_COMMIT_REF_NAME
  only:
    - tags
docker-deploy:
  stage: docker-deploy
  script:
    - make
    - docker build --rm -t 10.0.44.57:5000/risk/riskclient:$CI_COMMIT_REF_NAME .
    - docker push 10.0.44.57:5000/risk/riskclient:$CI_COMMIT_REF_NAME
  only:
    - tags