before_script:
  - go env -w GOPROXY=https://goproxy.cn,direct
  - go env -w GO111MODULE=on
  - go mod tidy
stages:
  - build
  - test
  - deploy
build:
  stage: build
  script:
    - make
  only:
    - tags
test:
  stage: test
  script:
    - echo $CI_COMMIT_REF_NAME
  only:
    - tags
deploy:
  stage: deploy
  script:
    - echo $CI_COMMIT_REF_NAME
  only:
    - tags