# 请不要在 aos 系统中 直接更新此配置
# 更新 riskengine 项目中的 pipeline.yaml 配置，然后同步到 aos 系统中
# 更新 pipeline 地址 https://aos.mfwdev.com/microservice/updateapp
# app id 3429
#
workspace:
  base: /go/

clone:
  git:
    image: docker.mfwdev.com/paas/drone-plugin-git:latest
    network_mode: host
    auth_config:
      innerid: hub.mfwdev.com

pipeline:
  build-kunkka:
    image: docker.mfwdev.com/paas/golang:1.11
    # WTF 必须有软连接 不想依赖环境变量
    commands:
      - ln -s /go/src/gitlaball.nicetuan.net/wangjingnan/golib/msales/riskengine /usr/local/go/src/riskengine
      - go build .
    network_mode: host
    auth_config:
      innerid: hub.mfwdev.com

  push-kunkka:
    image:  docker.mfwdev.com/paas/drone-docker:v0.5.2
    repo: hub.mfwdev.com/msales/riskengine
    dockerfile:  golang1.10.3-msales-riskengine-3429
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: host
    auth_config:
      innerid: hub.mfwdev.com
    auth_config_innerid: hub.mfwdev.com
