# 请不要在 aos 系统中 直接更新此配置
#
workspace:
  base: /go/

clone:
  git:
    image: docker.test.com/paas/drone-plugin-git:latest
    network_mode: host
    auth_config:
      innerid: hub.test.com

pipeline:
  build-kunkka:
    image: docker.test.com/paas/golang:1.11
    # WTF 必须有软连接 不想依赖环境变量
    commands:
      - ln -s /go/src/gitlaball.nicetuan.net/wangjingnan/golib/msales/riskengine /usr/local/go/src/riskengine
      - go build .
    network_mode: host
    auth_config:
      innerid: hub.test.com

  push-kunkka:
    image:  docker.test.com/paas/drone-docker:v0.5.2
    repo: hub.test.com/msales/riskengine
    dockerfile:  golang1.10.3-msales-riskengine-3429
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: host
    auth_config:
      innerid: hub.test.com
    auth_config_innerid: hub.test.com
